---
language: ruby

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false

rvm:
  - 2.5.8
  - 2.6.7
  - 2.7.3
  - 3.0.0

bundler_args: --jobs=3 --retry=3

install:
  - bundle install --retry=3

cache: bundler

script:
  - bundle exec rake
  - bundle exec codeclimate-test-reporter
